### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by lxl-riflebird** [fuchengwei/element-readonly-form-item#1]
![image](https://github.com/fuchengwei/element-readonly-form-item/assets/38177451/f9f57e3e-3601-4bbc-a238-d0354c1701e9)
![image](https://github.com/fuchengwei/element-readonly-form-item/assets/38177451/d9a3884c-16cf-40b1-a1c0-7ced30af0959)

**Comment by fuchengwei** [comment]
可以把这个项目发到我的邮箱吗 我本地调试一下

**Comment by lxl-riflebird** [comment]
已发你qq邮箱了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月29日(周二) 晚上7:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [fuchengwei/element-readonly-form-item] 编译报错 (Issue #1)




 
可以把这个项目发到我的邮箱吗 我本地调试一下

**Comment by fuchengwei** [comment]
已修复 升级到 1.11.0 版本即可
